import type { CatalogCard } from "./types.js";
import { rankCatalogCards } from "./cardSearch.js";

const CHASE_CARDS: CatalogCard[] = [
  {
    game: "POKEMON",
    language: "EN",
    name: "Charizard",
    setName: "Base",
    setCode: "base1",
    number: "4/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/4_hires.png",
    tcgApiId: "base1-4",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Blastoise",
    setName: "Base",
    setCode: "base1",
    number: "2/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/2_hires.png",
    tcgApiId: "base1-2",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Venusaur",
    setName: "Base",
    setCode: "base1",
    number: "15/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/15_hires.png",
    tcgApiId: "base1-15",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Lugia",
    setName: "Neo Genesis",
    setCode: "neo1",
    number: "9/111",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/neo1/9_hires.png",
    tcgApiId: "neo1-9",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Hitmontop",
    setName: "Neo Discovery",
    setCode: "neo2",
    number: "3/75",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/neo2/3_hires.png",
    tcgApiId: "neo2-3",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Mr. Mime",
    setName: "Base",
    setCode: "base1",
    number: "22/102",
    rarity: "Rare",
    imageUrl: "https://images.pokemontcg.io/base1/22_hires.png",
    tcgApiId: "base1-22",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Umbreon VMAX",
    setName: "Evolving Skies",
    setCode: "swsh7",
    number: "215/203",
    rarity: "Rare Secret",
    imageUrl: "https://images.pokemontcg.io/swsh7/215_hires.png",
    tcgApiId: "swsh7-215",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Rayquaza VMAX",
    setName: "Evolving Skies",
    setCode: "swsh7",
    number: "218/203",
    rarity: "Rare Secret",
    imageUrl: "https://images.pokemontcg.io/swsh7/218_hires.png",
    tcgApiId: "swsh7-218",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Charizard ex",
    setName: "151",
    setCode: "sv3pt5",
    number: "199/165",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    tcgApiId: "sv3pt5-199",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Mew ex",
    setName: "Paldean Fates",
    setCode: "sv4pt5",
    number: "232/091",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv4pt5/232_hires.png",
    tcgApiId: "sv4pt5-232",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pikachu ex",
    setName: "Surging Sparks",
    setCode: "sv8",
    number: "238/191",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv8/238_hires.png",
    tcgApiId: "sv8-238",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Giratina V",
    setName: "Lost Origin",
    setCode: "swsh11",
    number: "186/196",
    rarity: "Rare Ultra",
    imageUrl: "https://images.pokemontcg.io/swsh11/186_hires.png",
    tcgApiId: "swsh11-186",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Gengar",
    setName: "Lost Origin Trainer Gallery",
    setCode: "swsh11tg",
    number: "TG06/TG30",
    rarity: "Trainer Gallery Rare Holo",
    imageUrl: "https://images.pokemontcg.io/swsh11tg/TG06_hires.png",
    tcgApiId: "swsh11tg-TG06",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pikachu with Grey Felt Hat",
    setName: "Scarlet & Violet Black Star Promos",
    setCode: "svp",
    number: "SVP085",
    rarity: "Promo",
    imageUrl: "https://images.pokemontcg.io/svp/85_hires.png",
    tcgApiId: "svp-85",
  },
];

export function getChaseCards(): CatalogCard[] {
  return [...CHASE_CARDS];
}

export function searchChaseCards(query: string, setName?: string, limit = 8): CatalogCard[] {
  return rankCatalogCards(query, CHASE_CARDS, { setName, limit });
}
