import type { CatalogCard } from "./types.js";
import { rankCatalogCards } from "./cardSearch.js";

const CHASE_CARDS: CatalogCard[] = [
  {
    game: "POKEMON",
    language: "EN",
    name: "Charizard",
    setName: "Base",
    setCode: "base1",
    number: "4/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/4_hires.png",
    tcgApiId: "base1-4",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Blastoise",
    setName: "Base",
    setCode: "base1",
    number: "2/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/2_hires.png",
    tcgApiId: "base1-2",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Venusaur",
    setName: "Base",
    setCode: "base1",
    number: "15/102",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/base1/15_hires.png",
    tcgApiId: "base1-15",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Lugia",
    setName: "Neo Genesis",
    setCode: "neo1",
    number: "9/111",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/neo1/9_hires.png",
    tcgApiId: "neo1-9",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Hitmontop",
    setName: "Neo Discovery",
    setCode: "neo2",
    number: "3/75",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/neo2/3_hires.png",
    tcgApiId: "neo2-3",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Mr. Mime",
    setName: "Base",
    setCode: "base1",
    number: "22/102",
    rarity: "Rare",
    imageUrl: "https://images.pokemontcg.io/base1/22_hires.png",
    tcgApiId: "base1-22",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Umbreon VMAX",
    setName: "Evolving Skies",
    setCode: "swsh7",
    number: "215/203",
    rarity: "Rare Secret",
    imageUrl: "https://images.pokemontcg.io/swsh7/215_hires.png",
    tcgApiId: "swsh7-215",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Rayquaza VMAX",
    setName: "Evolving Skies",
    setCode: "swsh7",
    number: "218/203",
    rarity: "Rare Secret",
    imageUrl: "https://images.pokemontcg.io/swsh7/218_hires.png",
    tcgApiId: "swsh7-218",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Charizard ex",
    setName: "151",
    setCode: "sv3pt5",
    number: "199/165",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/199_hires.png",
    tcgApiId: "sv3pt5-199",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Zapdos ex",
    setName: "151",
    setCode: "sv3pt5",
    number: "192/165",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv3pt5/192_hires.png",
    tcgApiId: "sv3pt5-192",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Mew ex",
    setName: "Paldean Fates",
    setCode: "sv4pt5",
    number: "232/091",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv4pt5/232_hires.png",
    tcgApiId: "sv4pt5-232",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pawmi",
    setName: "Paldean Fates",
    setCode: "sv4pt5",
    number: "226/91",
    rarity: "Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv4pt5/226_hires.png",
    tcgApiId: "sv4pt5-226",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Flittle",
    setName: "Paldean Fates",
    setCode: "sv4pt5",
    number: "164/91",
    rarity: "Shiny Rare",
    imageUrl: "https://images.pokemontcg.io/sv4pt5/164_hires.png",
    tcgApiId: "sv4pt5-164",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pikachu ex",
    setName: "Surging Sparks",
    setCode: "sv8",
    number: "238/191",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/sv8/238_hires.png",
    tcgApiId: "sv8-238",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Giratina V",
    setName: "Lost Origin",
    setCode: "swsh11",
    number: "186/196",
    rarity: "Rare Ultra",
    imageUrl: "https://images.pokemontcg.io/swsh11/186_hires.png",
    tcgApiId: "swsh11-186",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Gengar",
    setName: "Lost Origin Trainer Gallery",
    setCode: "swsh11tg",
    number: "TG06/TG30",
    rarity: "Trainer Gallery Rare Holo",
    imageUrl: "https://images.pokemontcg.io/swsh11tg/TG06_hires.png",
    tcgApiId: "swsh11tg-TG06",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pikachu",
    setName: "Crown Zenith Galarian Gallery",
    setCode: "swsh12pt5gg",
    number: "GG30/GG70",
    rarity: "Trainer Gallery Rare Holo",
    imageUrl: "https://images.pokemontcg.io/swsh12pt5gg/GG30_hires.png",
    tcgApiId: "swsh12pt5gg-GG30",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Mewtwo VSTAR",
    setName: "Crown Zenith Galarian Gallery",
    setCode: "swsh12pt5gg",
    number: "GG44/GG70",
    rarity: "Special Illustration Rare",
    imageUrl: "https://images.pokemontcg.io/swsh12pt5gg/GG44_hires.png",
    tcgApiId: "swsh12pt5gg-GG44",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Charizard GX",
    setName: "Hidden Fates Shiny Vault",
    setCode: "sma",
    number: "SV49/SV94",
    rarity: "Rare Shiny GX",
    imageUrl: "https://images.pokemontcg.io/sma/SV49_hires.png",
    tcgApiId: "sma-SV49",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Blastoise",
    setName: "Evolutions",
    setCode: "xy12",
    number: "31/108",
    rarity: "Rare Holo",
    imageUrl: "https://images.pokemontcg.io/xy12/31_hires.png",
    tcgApiId: "xy12-31",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Blastoise EX",
    setName: "Evolutions",
    setCode: "xy12",
    number: "21/108",
    rarity: "Rare Holo EX",
    imageUrl: "https://images.pokemontcg.io/xy12/21_hires.png",
    tcgApiId: "xy12-21",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "M Blastoise EX",
    setName: "Evolutions",
    setCode: "xy12",
    number: "22/108",
    rarity: "Rare Holo EX",
    imageUrl: "https://images.pokemontcg.io/xy12/22_hires.png",
    tcgApiId: "xy12-22",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Pikachu with Grey Felt Hat",
    setName: "Scarlet & Violet Black Star Promos",
    setCode: "svp",
    number: "SVP085",
    rarity: "Promo",
    imageUrl: "https://images.pokemontcg.io/svp/85_hires.png",
    tcgApiId: "svp-85",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Victini",
    setName: "Scarlet & Violet Black Star Promos",
    setCode: "svp",
    number: "SVP208",
    rarity: "Promo",
    imageUrl: "https://images.scrydex.com/pokemon/svp-208/large",
    tcgApiId: "svp-208",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Snivy",
    setName: "Mega Evolution Promos",
    setCode: "mep",
    number: "MEP049",
    rarity: "Promo",
    imageUrl: "https://images.scrydex.com/pokemon/mep-49/large",
    tcgApiId: "mep-49",
  },
  {
    game: "POKEMON",
    language: "EN",
    name: "Alakazam",
    setName: "Mega Evolution Promos",
    setCode: "mep",
    number: "MEP0079",
    rarity: "Promo",
    imageUrl: "https://images.scrydex.com/pokemon/mep-79/large",
    tcgApiId: "mep-79",
  },
];

export function getChaseCards(): CatalogCard[] {
  return [...CHASE_CARDS];
}

export function searchChaseCards(query: string, setName?: string, limit = 8): CatalogCard[] {
  return rankCatalogCards(query, CHASE_CARDS, { setName, limit });
}
